### ISSUE TITLE
setup gha for jupyter-book with mamba lockfiles

### ISSUE THREAD

**Issue by phaustin** [UBC-DSCI/introduction-to-datascience-python#1]
working:

https://github.com/UBC-DSCI/introduction-to-datascience-python/blob/myst/.github/workflows/build_book.yml

**Comment by phaustin** [comment]
first version working

**Comment by ttimbers** [comment]
~~The link above is broken now? Or I don't have access?~~

Ahh, I think the `myst` directory is not there anymore, so it should be: https://github.com/UBC-DSCI/introduction-to-datascience-python/blob/main/.github/workflows/build_book.yml
