### ISSUE TITLE
Add plotly to the docker image

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#127]
I think plotly may be missing. The pre-rendered images from when the MDS students were doing their pass are still committed though, and they're fine, so no need to do this right now.

**Comment by joelostblom** [comment]
Yup I can confirm that it is missing. Running `docker run --rm -v $(pwd):/home/jovyan ubcdsci/py-intro-to-ds:20230104230634037f38 /bin/bash -c "python -c 'import plotly'"` returns `ModuleNotFoundError: No module named 'plotly'`. Fixing this should fix #83 as well.
