### ISSUE TITLE
Inconsistent glue number format

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#132]
You can see the two that generally show up here:

![image](https://user-images.githubusercontent.com/5981307/211985227-ded364ba-0d71-4ad8-9c2d-50eff0d3ba86.png)

**Comment by trevorcampbell** [comment]
seems related to whether you pass a number into glue or a string (which you format yourself manually using `.format`)

**Comment by joelostblom** [comment]
I remember talking to gloria about this before, I think we might want to always use `{glue:text}` https://jupyterbook.org/en/stable/content/executable/output-insert.html#the-glue-text-role?

**Comment by trevorcampbell** [comment]
See #79 also.

**Comment by trevorcampbell** [comment]
Turns out with the current book, in classification 1:
```
{glue:text}`benign_count`
```
typesets like 

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/5981307/c576f3d6-75eb-4283-b45c-96197fb6b48c)

while
```
{glue:}`benign_count`
```
typesets like

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/5981307/522caad8-9df0-4bdf-9a82-81cea726859a)

which I prefer (no bolding). But this depends on the input type. I will check through the remainder of the book for inconsistent formatting and try to make it all "plain" looking (if possible).

**Comment by joelostblom** [comment]
Nice! I agree that "plain" looking is preferred.

**Comment by trevorcampbell** [comment]
Ah! So the best solution turns out to be to change the font style in `static/style.css` to
```
span.pasted-text {
  font-weight: normal;
}
```

Which keeps the ability to do nice formatting of numbers using `glue:text` while avoiding bolding. I'll go through and check that all numbers get pasted as text with whatever formatting is appropriate in #257
