### ISSUE TITLE
Talk about how to handle large data sets in Altair

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#136]

**Comment by trevorcampbell** [comment]
I think this might be outside the scope of this book, and I'm not sure where it would fit well. I can be convinced otherwise :)

**Comment by joelostblom** [comment]
I would like to mention this briefly because I think it can be a common point of confusion. Once we are able to update to 5.1+ in the worksheets and use vegafusion there instead of `disable_max_rows`, we could add a short paragraph in the viz chapter:

> By default, Altair will raise an error if you try to plot a data frame with more than 5,000 rows. The simplest way to plot larger data sets is to enable the `vegafusion` data transformer by including this line just after you import the Altair package: `alt.data_transformers.enable("vegafusion")`. This data transformer will allow you to plot up to 100,000 graphical objects (e.g. a scatter points with 100,000 points). To plot even larger datasets, see [the Altair documentation](https://altair-viz.github.io/user_guide/large_datasets).

**Comment by trevorcampbell** [comment]
@joelostblom note that the final copy of this for 1st edition publication is due to the publisher by end of this year. What's the likelihood of getting that in before that?

(I'm fine with adding the paragraph you wrote in a note box somewhere in viz, assuming it flows OK)

**Comment by joelostblom** [comment]
I think putting that paragraph in can be done before that. It will just not apply to our students until the student server is updated, but it will be relevant to everyone else reading the book.

**Comment by trevorcampbell** [comment]
I'm OK with that
