### ISSUE TITLE
Figures to be modified in Intro Chapter

### ISSUE THREAD

**Issue by nd265** [UBC-DSCI/introduction-to-datascience-python#15]
Some figures specific to explanation of syntax need to be modified/discarded in the Python notebook. For example: `read_csv`, `arrange`, etc 
Have only included `read_csv` image in the Python notebook as that was the closest to R and decided not to include for the others
Furthermore, the teaching team needs to decide what to do for these kind of images in the Introduction chapter

**Comment by joelostblom** [comment]
Closing as we have other issues tracking the image modifications now
