### ISSUE TITLE
confusion matrix approach

### ISSUE THREAD

**Issue by lheagy** [UBC-DSCI/introduction-to-datascience-python#164]
In the textbook, we use `pd.crosstab` for building the confusion matrix, but the worksheet and tutorial use `ConfustionMatrixDisplay` from scikit-learn (`sklearn.metrics`). We should choose one to be consistent with

**Comment by trevorcampbell** [comment]
@joelostblom is this one handled now? I recall us making edits to it

**Comment by joelostblom** [comment]
Yup I updated everything to use `crosstab` instead of `confusion_matrix` for showing the array/df. Then we use `ConfusionMatrixDisplay.from_estimator` to plot
