### ISSUE TITLE
Update to Altair 5

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#167]
Altair 5 was recently released and it fixes some issues from before (like more reliable saving and working with large datasets, https://altair-viz.github.io/releases/changes.html), as well as introduces a more convenient (optional) syntax for parameter options. I'm happy to make the changes if we are OK updating the package on our service for the fall. This should be done after #160 is merged imo.

**Comment by trevorcampbell** [comment]
New image on the `main` branch uses Altair 5 -- I needed to rebuild it while working on PDF builds. If we need to bring it back to an earlier version we can pin it and rebuild the image.

**Comment by joelostblom** [comment]
That's great! Could I go ahead an update to the more succinct syntax after we merge #160? The main change is that option parameters now can be written as methods, so something redundant like 

```
x=alt.X('Horsepower', axis=alt.Axis(tickMinStep=50))
```

could instead be written as 

```
x=alt.X('Horsepower').axis(tickMinStep=50)
```

**Comment by trevorcampbell** [comment]
Sounds like a good idea to me!
