### ISSUE TITLE
Add a README and LICENSE?

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience-python#17]
Should we add a README that explains tooling and how to build the book for PDF and HTML? A LICENSE is pretty important too... We should adopt the same one we use for the R book I think (that would be CRC Press's preference).

**Comment by trevorcampbell** [comment]
+1 to all of the above. For the license we should do that now and use the same one as for the R book. For build instructions, probably should wait until the code has settled a bit -- content/workflows still in flux.

**Comment by trevorcampbell** [comment]
Done
