### ISSUE TITLE
Fix render of interactive images in PDF

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#175]
From @trevorcampbell 's review of https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/160/files

> Is it possible to render a different image in the PDF version of the book that is just a static screenshot of what the tooltip would look like? If not immediately, please open an issue to sort that out (and anywhere else we add interactive figures where it's important that the interactivity is displayed -- though I think it will only matter here in Ch4)

> stuff like "hover over things with the mouse" do not look great in a printed / PDF book

**Comment by trevorcampbell** [comment]
In #240 I am fixing the 3d render in the HTML version. But we will still need to do two things:
- use the new `BOOK_BUILD_TYPE=PDF` flag (check in preamble py script) to detect when we're in a PDF build, and switch to a static `.png` render of these
- get rid of "hover over these with mouse" statements in viz

**Comment by joelostblom** [comment]
> get rid of "hover over these with mouse" statements in viz

Should we get rid of these completely or just in the PDF version via something like `sed` in the build script? A simple approach could be to just mention organically in the text that the hover is only available in the online version of the book?

**Comment by trevorcampbell** [comment]
Let's get rid of it completely. We should really limit inconsistencies/special cases between PDF and HTML. We don't need to tell people to hover, they can figure it out themselves.
