### ISSUE TITLE
Thoughts for plot and image color choices

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience-python#18]
In the eventuality that the Python version of this book makes it to print one day, we should make sure all colors we choose for plots and images look nice in both RGB and CMYK. This was wisdom we lacked for the first version of the R book, and because the book must be print in CMYK, we ended up with some figures looking a bit less than ideal (see example [here](https://github.com/UBC-DSCI/introduction-to-datascience/issues/438)).

**Comment by trevorcampbell** [comment]
Agreed!

**Comment by trevorcampbell** [comment]
Update: we tried to do everything in CMYK, but it causes so many other issues with file formats, web rendering, etc that it's just not worth it. 

Plan now is to do everything with PNG in RGB, but manually check CMYK conversion to make sure everything will look reasonable in print too.
