### ISSUE TITLE
Images of saved charts are from ggplot

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#180]
At the end of the viz chapter, we compare svg and png by showing an image of both zoomed in. However that image is from the ggplot chart and does not look the same as the python charts we created, so it might be unclear for students why the saved chart changed from blue circles with a white background to black dots with a grey background.

Image in book:
![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/0def45a7-cfce-4ad7-988f-061b71baefca)

Actual saved chart:
![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/d1621d69-53ee-456d-b009-195f99d15ef0)

**Comment by trevorcampbell** [comment]
see also #147
