### ISSUE TITLE
Install vl-convert-python instead of altair-saver on the image/server

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#181]
@trevorcampbell With altair 5, the package that enables saving of charts is `vl-convert-python` rather than `altair-saver` so we should update this on the docker image (and dsci 100 server for the fall)

**Comment by trevorcampbell** [comment]
Fixed in 018157a  (github actions will add a few more commits to update scripts / rebuild docker image automatically)

Please merge `main` into your working branch so that the `build_html.sh` and `build_pdf.sh` scripts use the updated Docker image.

**Comment by trevorcampbell** [comment]
(dsci-100 course images don't install saver, so no need to update those)
