### ISSUE TITLE
vendor the csv file for py_tutorial_classification1?

### ISSUE THREAD

**Issue by phaustin** [UBC-DSCI/introduction-to-datascience-python#2]
looks like columns have changed on https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt
which breaks https://github.ubc.ca/UBC-DSCI/dsci-100-instructor/blob/py_tutorial_classification1/source/py_tutorial_classification1/py_tutorial_classification1.py#L631-L634

should we host our own versions of these?

**Comment by joelostblom** [comment]
I tested a bit and the issue seems to be that some line uses multiple `\t` as value separators instead of just one. We can fix this by using the python engine and a regex for the separator:

```python
pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt",
    delimiter="\t+",
    names=names,
    engine='python'
)
```

**Comment by joelostblom** [comment]
PR here, not sure how to autolink to this issue since it is in another repo https://github.ubc.ca/UBC-DSCI/dsci-100-instructor/pull/543

**Comment by phaustin** [comment]
lgtm
