### ISSUE TITLE
Inconsistent axis label code style

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#224]
I've noticed that the code isn't consistent between `alt.Y('blah').title('blah')` and `alt.Y('blah', title='blah')` -- I noticed this in inference but it could be more pervasive. I think the newer style is `alt.Y('blah').title('blah')`, so we should switch everything over to that.

I think all the instances of that inconsistency are in remove-cell tagged cells, so not the end of the world, but it would be good to ensure that code is consistent throughout, even in hidden cells

**Comment by joelostblom** [comment]
Yup I almost only fixed what was visible in the book since the other syntax is still valid and it made the important changes stand out more. I agree it would be nice to have it the same everywhere, especially when grepping for something, but agree that this is low prio.
