### ISSUE TITLE
Talk more about goodness of fit or change worksheet

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#231]
One of the regression assignments has a question of whether R2 is measure of goodness of fit or prediction error, but we odn't describe the differences in the textbook and barely mention goodness of fit at all

**Comment by trevorcampbell** [comment]
~~@joelostblom please open this issue in the instructor repo to modify the worksheet~~

nevermind I will just open one now and link here
