### ISSUE TITLE
Be consistent in how we fit models

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#233]
The textbook and assignments have a variety of ways to fit models currently, including:

```
m = M()
m.fit()
```

```
m = M()
m = m.fit()
```

```
m = M().fit
```

I think this can be confusing and it would be nice if we could standardize on one main approach. My vote would be on the first one, since it separates the initialization and fitting into two separate steps and avoids reassignment of the fitted object which makes it clear it is modified in place. There are a few instances with list comprehensions where we still need the third approach and we can make this explicit when we use it "here we initialize and train the model in one line". The second approach could be avoided completely.

**Comment by trevorcampbell** [comment]
See #134
