### ISSUE TITLE
Use light background by default

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#235]
The background of the book still seems to follow the system theme by default:

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/608b4586-4da5-4a36-a80a-080fee75972e)

I think light looks much better, especially with the charts having light backgrounds. I thought I fixed this here https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/218/files#r1311579781 according to https://github.com/executablebooks/jupyter-book/issues/1430#issuecomment-1511877161 but it seems to not have an effect.

I've tried two different browsers and clearing my chache. Will restart my laptop next

**Comment by trevorcampbell** [comment]
We should just keep the system default TBH. No reason to force users to use lightmode when they want darkmode. Not really our problem if the white figure bkgs don't look as good there (and honestly, they don't look that bad anyway).

Closing, but feel free to re-open if you feel strongly
