### ISSUE TITLE
Standardize syntax for visualizations

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#29]
Just a few comments on the varying styles of the viz specs I have seen in different chapters. I think we should write as close to the documentation as possible to make students used to that syntax. There are some pep8 issues I am guess we will fix with black (e.g. same quotes everywhere and no spaces around parameter assignment operators).  Black is used for the altair docs (I think that is with the default settings) and does not complain about the syntax in those specs

I would suggest that an example spec like this:

```py
alt.Chart(islands_top12).mark_bar(color='black').encode(
    x = alt.X("size",title = "Size (1000 square mi)"),
    y = alt.Y("landmass", title = "Landmass", sort='x'),
    color = alt.Color("landmass_type", title = "Some long title", scale=alt.Scale(zero=False))).configure_axis(
    titleFontSize=12).transform_filter(brush)
```

would be reformatted to something like this for better readability:

```py
alt.Chart(islands_top12).mark_bar(color='black').encode(
    alt.X('size', title='Size (1000 square mi)'),
    alt.Y('landmass', sort='x', title='Landmass'),
    alt.Color(
        'landmass_type',
        scale=alt.Scale(zero=False),
        title='Some long title'
    )
).configure_axis(
    titleFontSize=12
).transform_filter(
    brush
)
```

I think we discussed the syntax for these a long time ago, and considered something different from the docs, but I have since started to write the same way as in the docs with the leading parenthesis for chains, and it is very convenient, even for long pandas chains. I *think* this is what we talked about originally:

```py
(
    alt.Chart(islands_top12)
    .mark_bar(color='black')
    .encode(
        alt.X('size', title='Size (1000 square mi)'),
        alt.Y('landmass', sort='x', title='Landmass'),
        alt.Color('landmass_type',
                  scale=alt.Scale(zero=False),
                  title='Some long title')
    .configure_axis(titleFontSize=12)
    .transform_filter(brush)
)
```

Just my thoughts, open for other ideas.

**Comment by trevorcampbell** [comment]
+1 for your suggested syntax -- but lets hold off on doing this until after we do major edits for Jan 2023.

Then we should make a style guide for this book (similar to the one that the R book has)

**Comment by trevorcampbell** [comment]
@joelostblom is this handled now?

**Comment by joelostblom** [comment]
Yup, done and done
