### ISSUE TITLE
To-do: Chapter reading - web scraping

### ISSUE THREAD

**Issue by GloriaWYY** [UBC-DSCI/introduction-to-datascience-python#31]
[From this section on](https://ubc-dsci.github.io/introduction-to-datascience-python/reading.html#obtaining-data-from-the-web), the text has not been converted to Python version yet.

**Comment by GloriaWYY** [comment]
The first draft is ready in PR #32

**Comment by trevorcampbell** [comment]
Merged -- thank you!
