### ISSUE TITLE
Text in 10.4 needs updating to match the new code

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#320]
I thin we updated the code but forgot about the text

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/40b97ff1-9b21-4377-87a1-0151c408ddd6)

**Comment by trevorcampbell** [comment]
Since this is fairly minor I'll fix in #317

**Comment by trevorcampbell** [comment]
Fixed in [8396473](https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/317/commits/83964733ccab4faf911b4bba64763366c670827c)
