### ISSUE TITLE
The great ( :bug: ) hunt: Ch5

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#322]
- [ ] Clicking on the reference to cover and hard, and Fix and Hodges takes me to the bibliography in Ch7 (the last time this ref is used maybe?). Other refs stay in ch 5.
    ![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/5017469f-1c52-4def-9bfd-05c3c7738602)
- [ ] Clicking on the reference to Street et all in Ch5, takes me to the bibliogrpahy in ch6. Other references stay on the same page
    ![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/c10531ed-b839-4472-9ae8-5289b6279f92)
- [ ] We mention the counts and percentages but the code cell only shows percentage.  I don't think it is a big deal since the counts code cell come just a paragraph later 
    ![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/4a76f578-b286-4b8c-8bd1-4d103c907093)
- [ ] When I click on Fig 5.1, is for some reason takes me to the figure caption instead of the figure (so the caption is a the top of the page and the fig not visible. other figs show the figure). Fig 5.11 and 5.15 have this issue too.
- [ ] Table 5.1 has the caption above the table, but all figures have the caption text below the figure. Maybe not important either.
- [ ] For fig 5.6, it seems like the red diamond point is slightly to the left of x=0, but we use exactly 0 in the table computation (again probably not of great importance)
- [ ] In section 5.6, we use the term "fit" for the first time in this sentence "In order to fit the model on the breast cancer data", maybe we can rewrite to "In order to train (also called "fit") the model on the breast cancer data", since we have used the word "train" previously in the chapter.
- [ ] While the following statement in 5.6 is generally true for `fit`, I think it is less true for KNN since the computation for the nearest neighbors happens for each point during predict. `fit` still does the data structure setup, but I'm not sure if that can be described as "all the heavy lifting" (probably also a minor point though).
    - "Note that the fit function might look like it does not do much from the outside, but it is actually doing all the heavy lifting to train the K-nearest neighbors model, and modifies the knn model object.
- [ ] The caption of fig 5.9 says "Fig. 5.9 Comparison of K = 3 nearest neighbors with standardized and unstandardized data." However the order of the charts in the figure is the opposite (unstandardized first) so we could consider swapping them in the caption too.
- [ ] In 5.7.2 we say  "We choose these 3 observations using the .head() method, which takes the number of rows to select from the top (n).", but we actually don't type out `n` in the code, so maybe just leave it out here too would make it less confusing?
- [ ] Minor suggestion to add the bolded text: "[Fig. 5.13](https://python.datasciencebook.ca/pull317/classification1.html#fig-05-upsample-2) shows what happens if we set the background color of each area of the plot to the predictions the K-nearest neighbors classifier would make **if there was a new observation at that location**"

**Comment by ttimbers** [comment]
I think you also want to make these same figure caption improvements as in the R book: https://github.com/UBC-DSCI/introduction-to-datascience/issues/572
