### ISSUE TITLE
Bug hunt: preface, acknowledgements 

### ISSUE THREAD

**Issue by lheagy** [UBC-DSCI/introduction-to-datascience-python#324]
**Preface**
- Do we want the full url: `https://worksheets.python.datasciencebook.ca;` in the text, or just `worksheets.python.datasciencebook.ca` hyperlinked? 

**Acknowledgments**
- hypyerlink UBC in first paragraph? 
- Acknowledgements for the Python section: Add a thanks to Earth, Ocean and Atmospheric Sciences after Stats? (might be appreciated, esp as Phil and others spent some of their committee time working with the students on the first translation)

**Comment by trevorcampbell** [comment]
I like the https, so will add that. Will add EOAS acks too. Won't add UBC hyperlink (we actually used to have it, but it just clutters the PDF version)
