### ISSUE TITLE
Correct explanation of `read_table`

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#36]
`read_table` is not a more flexible version of `read_csv`, it is the same function with a different default for the `sep` param. I think it is easier to just stick to `read_csv` and show how to change `sep`.

**Comment by trevorcampbell** [comment]
This is probably a bit of a hold-over from the R version. I agree we should stick with `read_csv` and just change the sep. Let's do a global pass for this after chapter-specific stuff.
