### ISSUE TITLE
Suggestions for Ch 1 - Pandas intro

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#37]
These are all suggestions, some might seem more harshly written, but that is just to be succinct and write quickly.

- [x] "Python and THE pandas" -> "Python and pandas"
- [x] Elaborate on pd import alias
- [x] Fig 2 is the R-version and the font is too small
- [x] Remove print statements under "Naming things"
- [x] Variable names can't use `.`
- [x] Switching to `-` instead of `+` is a more natural example for non-working var names.
- [x] Data frames (>60 rows) are not printed just as the first few rows in Python, it also include the last few rows and a `...` that could use an explanation. And the number of rows and columns are printed at the bottom, not top.
- [x] Mention that single and double quotes are exchangeable to avoid confusion
- [x] The corresponding figures to 1.3 and up, in the R book are all missing in python.
- [x] Should we explain `.query` or `[]`? The former has some advantages in clearer chaining syntax, but is not as well documented.
- [x] "greatest to least" -> "largest to smallest value"
- [x] Introduce the contrast of df.method versus pd.function. Dataframes have the most important functions built-in which is great for finding help and what you're looking for.
- [x] "introduce tidy data in Chapter Cleaning" -> "introduce tidy data in THE Chapter Cleaning"
- [x] "A bar plot is a chart where the heights of the bars" -> "A bar plot is a chart where the LENGTHS of the bars".
- [x] R - Isn't stat == identify the default for bar? Or is that column? And does it even matter with one value?
- [x] The Python explanation for how expressions can continue on another line is wrong. It is not the `.`, it is the open paren (which is preferred over "\")
- [x] Better explanation of alt.X and alt.Y, take from 531 lecture notes.
- [x] I think the organization of the bars could benefit from having the largest bar closest to the axis.
- [x] Visualization syntax in "putting it all together" is off
- [x] Discuss the most common ways of getting help in JupyterLab, shift+tab and the contextual explorer. `?` also works in place of `help` in ipython, I don't think printing the docstring is worth teaching.
- [x] Exercises mention "R and the tidyverse"
- [ ] https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/35
- [ ] https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/34
- [ ] https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/29

**Comment by trevorcampbell** [comment]
@joelostblom "Better explanation of alt.X and alt.Y, take from 531 lecture notes."

can you paste that here pls?

**Comment by trevorcampbell** [comment]
Actually, just file a new issue for it -- what is there right now in Chapter 1 is good enough for running the course. We can (and should) make enhancements later.

**Comment by trevorcampbell** [comment]
The separate issue threads I think again are "nice to have"s, but not mandatory for the first run of the course, so checking them all off

**Comment by joelostblom** [comment]
Yes I can open a new issue for that! I think it's useful if we open new issues or leave unchecked all the things we don't implement just so that we can keep track of it and decide if we want it later.

**Comment by trevorcampbell** [comment]
That's what I've been doing -- "checked off" means either handled in the upcoming PR or spun out into its own issue for later.
