### ISSUE TITLE
reading

### ISSUE THREAD

**Issue by nd265** [UBC-DSCI/introduction-to-datascience-python#4]
Progress:

Basic code has been converted from R to python. The conversion of text specific to R still needs to be converted to python. All the data files required for reading purpose have been pushed to the data folder. Have kept some R code still in the notebook and will take action on it after confirmation. The changes can be found on the `reading` branch of this repository in file `reading.md`

Issues and doubts regarding the `Reading` chapter:

- [x] `reading.py` not getting updated after building the `reading.md` file with `jb build reading.md`. 
- [x] What is the meaning of `\index{loading|see{reading}}\index{reading!definition}`, I think this is something specific to R markdown?
     - see https://jupyterbook.org/en/stable/content/content-blocks.html#indexes
- [x] Should the documentation only specific to R be deleted?
- [x] What to do regarding the absolute path, when reading `happiness_report.csv`
- [x] Should the column names be included while reading from `data/can_lang-meta-data.csv`
- [x] No need for `read_delim` dection, as it is already covered in the previous section using `sep=\t`, or should I just replace the documentation with - 'Any delimiter can be used with `sep=''`'
- [x] 3 ways of assigning column names- while reading(using `names=`), using `rename`, and using `df.columns`. which one to be used here? In the python tutorial, I saw `names` being used, but in `R`, `rename` is being used, so confused, which one to use
- [x] Installation of openpyxl, pgdb
- [x] What to do about `lazy evaluation` and `collect`, as python can read from Postres simply. should these be deleted from the documentation?
- [x] As the server `fakeserver.stat.ubc.ca` is an alias, the code in the python code-cell would error out, so should the code be in commented form?
- [x] To find the `min` of `average_rating`, can it be done in just one code cell? Unlike done in R?
- [x] What to do about additional resources section and exercises?
- [x] Confirm: I am reading images using the Myst syntax : 

```
{figure} ./path/to/figure.jpg
:name: label
caption
```
  - see https://jupyterbook.org/en/stable/content/figures.html#markdown-figures for a better approach

**Comment by ttimbers** [comment]
>What is the meaning of \index{loading|see{reading}}\index{reading!definition}, I think this is something specific to R markdown?
see https://jupyterbook.org/en/stable/content/content-blocks.html#indexes

These are flagging terms to be included in the index. They LaTeX and can also be used in Jupyter book (see this example here: https://github.com/py-pkgs/py-pkgs/blob/main/py-pkgs/03-how-to-package-a-python.ipynb)

**Comment by nd265** [comment]
### Progress

1. Have converted all code to python and corresponding text as well
2. Have added `tags` in the code cells to hide output of some cells or not show it at all
3. As discussed in the previous call, have left the `\index{}...` untouched as the course of action for it is yet to be decided
4. As discussed in the previous call, have left the optional sections starting from `Obtaining data from the web` until the end of the chapter `Additional Resources` untouched, as it is yet to be decided by the teaching team.


### Queries
- [x] What is to be done for the large output returned by the SQL query? Is it to be truncated? or completely shown.
- [x] What is to be done regarding the figure that shows the data referencing in R (it uses terms like tibble and the captions are part of the figure, which are specific to R)
Example:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/35167740/169984295-fa0da861-df7a-4881-abd9-c8c61bb4f742.png">

- [x] In Postgres section, the output in the R notebook is R specific, so to get a python specific output, can the actual server credentials be provided on which the queries can be executed, or the R specific output suffices? 
Example: 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/35167740/169984101-0a74021b-4c5b-4012-84f4-b9e1e3871af0.png">
