### ISSUE TITLE
Change dev/main branch structure

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#47]
I realized today that it would probably be more natural to have the following:
- get rid of `dev` branch
- treat current `main` branch as `dev`
- create a new `prod` branch for production pushes (which then auto-push built page to `gh-pages` as usual)

That way we avoid accidental direct commits and PRs into our production branch (since `main` is the default branch for most things)

In order to do this, note that we'd need to change some github actions

**Comment by joelostblom** [comment]
I wholeheartedly agree with this. I think having the main branch for development and use releases/tags and separate branches for things like deployment makes the most sense.

**Comment by trevorcampbell** [comment]
This is completed now. Closing
