### ISSUE TITLE
R translation error: wrong URL to github repo

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#52]
Do a pass through the book for `github.com/ubc-dsci/introduction-to-datascience` links, which are for the R version of the book.

**Comment by trevorcampbell** [comment]
I will fix this now in #48 and #49, but need to check more globally later.

**Comment by joelostblom** [comment]
I grepped the repo for this string and even just the last part, but couldn't find any remaining incorrect references so closing this
