### ISSUE TITLE
"property" is the wrong name for `.loc[]`, `[]` and `.iloc[]`

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#55]
I see a lot of text say things like "the `loc[]` property"

I am replacing this throughout chapters 1 and 2 with things like "the `.loc[]` operation" which I think is more correct

Should apply this fix more globally after our current (Dec 2022) polish pass on individual chapters is done

**Comment by joelostblom** [comment]
I like this change, I agree that "operation" is more useful even if I believe either `property` or `attribute` (and even `method`) are correct as well.

On a related topic, will we differentiate `method` and `function` in dsci 100 or just call everything a function for simplicity? 
![image](https://user-images.githubusercontent.com/4560057/208274493-08d31e71-ebb8-43f4-ad39-04e71e092dce.png)


We might a little intro section on all the build-in functionality in a dataframe; it is not just something that we perform operations on, it comes with it's own built-in operations that we can access with the `.` syntax.

**Comment by trevorcampbell** [comment]
@joelostblom that is something to do in Chapter 3, I think. Ch1 is for quickly going all the way from point A to point B to produce a useful analysis without dwelling on nitty-gritty. Ch3 is I think the right place to get into the weeds on methods, dot syntax, etc

**Comment by joelostblom** [comment]
Yes, I agree we should not getting into that in ch1. I was more wondering if we should do it in a later chapter or not at all. We will probably not explain anything about classes versus other objects so not sure there is much use of differentiating methods and functions. But I personally find that it is hard not to say "method" when speaking, since that is the correct term =p

**Comment by trevorcampbell** [comment]
I just looked into this -- there are no more uses of "property" that I disagree with -- closing
