### ISSUE TITLE
Code fence boxes for data should have `code` tag

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#58]
In certain places in the text, we load dataframes and typeset them in code fences. But if we just use \``` as the first fence, the box will get code-like syntax highlighting (which isn't desirable for data frames). We need to look through the book and make sure code fences for data frames start like \```code   (which, unintuitively, typesets *without* syntax highlighting). I am fixing this in Ch 1 and 2 as part of #48 and #49 but we should do a global pass after polish round is done.

**Comment by joelostblom** [comment]
I think we can also use `text` instead of `code` if we want it to be more semantically intuitive (but not difference in output I believe)

**Comment by trevorcampbell** [comment]
I tried `text` (that was the obvious choice) and it didn't work! Still weird syntax highlighting. If `text` indeed works, I would prefer it.

(maybe this was in a flurry of activity and I wasn't paying enough attention to the build though...)

**Comment by trevorcampbell** [comment]
As a side note, jupyterbook spits out a warning that it doesn't understand `code` tag -- which is why you don't get any syntax highlighting in that case ;) I imagine `text` should work, but needs investigation and we can punt it for later.

**Comment by trevorcampbell** [comment]
resolved in #189
