### ISSUE TITLE
"method", "attribute", "function", etc

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#65]
At some point (once the major rounds of polish are done), we should make a decision on:
- what convention we want for using the terms method, function, attribute, object, member, etc
- when we introduce that explicitly (do we just gloss over it at the beginning without explaining and then introduce later explicitly? do we introduce explicitly when we first mention? etc)

This is definitely a low-priority item for after the first run in the Jan 2023 semester.

**Comment by joelostblom** [comment]
I was worried using the term `method` in the textbook because I think we never properly introduce it, but going through the worksheets I noticed that there is a mention in the into worksheet:

> The upper method we used here is different from the functions we used previously (e.g. print). This method is called using the dot notation (string.upper()), because this method only works for a particular kind of object that they were designed to work for. Here the upper method was written to only work with string objects. print function, however, was written to work with many kinds of objects, therefore, we don't use the dot notation.

**Comment by trevorcampbell** [comment]
See also #243
