### ISSUE TITLE
Assign to variables less often

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#68]
Minor suggestion. After looking over the first chapter again, I wonder if we need to assign the data frames and charts to variables as often as we do. I find that doing this creates unnecessary syntax for students to look at.

For example, instead of

```
ten_lang = arranged_lang.head(10)
ten_lang
```

it's simpler and more to the point to just have

```
arranged_lang.head(10)
```

**Comment by trevorcampbell** [comment]
I don't think we should worry about this right now. Let's revisit later.

(one argument for later: in Ch1 more naming things is used to reinforce the concept of assignment and objects with names)

**Comment by trevorcampbell** [comment]
this is fine as-is. we did reduce the naming things by quite a bit in later chapters, and I think it's fine to name things regularly in earlier chapters to reinforce assignment
