### ISSUE TITLE
Removing deprecation warnings

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#80]
Some `altair` code spits out a deprecation warning currently.

To suppress these, I'm currently including the code

```
{code-cell} ipython3
:tags: [remove-cell]
import warnings
def warn(*args, **kwargs):
    pass
warnings.warn = warn
```

to just eat all the warnings. But later once `altair` updates / book stabilizes, we should delete this code and make sure we aren't skipping over any important warnings.

**Comment by joelostblom** [comment]
Two thoughts on this:

1. I think we can use the following to just suppress the deprecation warning and not risk missing something important:
    ```py
    import warnings
    warnings.filterwarnings("ignore", category=DeprecationWarning)
    ```
2. Regardless of how we suppress the warnings in the book, students will still see them when they work with JupyterLab, so it could still be a good idea to restrict pandas to <1.5 on the server to avoid students getting confused by always seeing that warning when they use altair.

**Comment by trevorcampbell** [comment]
> I think we can use the following to just suppress the deprecation warning and not risk missing something important:

This is actually what I tried originally, but it didn't work. I will try it again...

> Regardless of how we suppress the warnings in the book, students will still see them when they work with JupyterLab

This is not an issue. I'm more concerned about the polish on the book -- if anyone is scared of these warnings in class we can just explain it to them.

**Comment by trevorcampbell** [comment]
needed

```
warnings.filterwarnings("ignore", category=FutureWarning)
```

to actually prevent the altair warnings

**Comment by joelostblom** [comment]
This has been added to all the relevant chapters so closing the issue
