### ISSUE TITLE
Figure captions and whitespace

### ISSUE THREAD

**Issue by lheagy** [UBC-DSCI/introduction-to-datascience-python#87]
Many of the figures have the label `caption-hack`. This removes margin space, and in some places led to overlapping figure and caption. Instead, we should 
- [ ] remove the `caption-hack` tag
- [ ] trim whitespace on figures

https://github.com/UBC-DSCI/introduction-to-datascience-python/blob/313af482cfc6695369a1a8c600f1ae0fe08ab646/source/_static/style.css#L7-L9

![image](https://user-images.githubusercontent.com/6361812/210280578-82f0370b-5fad-460d-81d0-6d69c903625d.png)

This has been addressed in Ch 3 with #76, but will need to be addressed elsewhere.

**Comment by joelostblom** [comment]
Just a note that the `caption-hack` CSS class might still be needed for any images that are automatically generated by code blocks, such as our Altair charts. See the following for details as to why and the alternative approach we can use:

- https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/5
- https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/3

**Comment by trevorcampbell** [comment]
I believe this is handled now
