### ISSUE TITLE
code should be inside of "Note" box

### ISSUE THREAD

**Issue by lheagy** [UBC-DSCI/introduction-to-datascience-python#88]
The code in Ch3 just before the section on "Data structures in Python" should be inside the "note" box. I am not sure how to do this in jupyterbook

**Comment by trevorcampbell** [comment]
We should do a pass for this throughout the whole book -- I'm fairly sure I saw that issue elsewhere

**Comment by trevorcampbell** [comment]
This would be solved if we did #91
