### ISSUE TITLE
Fix permissions on source

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#89]
For some reason source is set to be writable by other users than the owner and group. I don't think there is any good reason for this so we should set it back to permissions 775 at some point.

![image](https://user-images.githubusercontent.com/4560057/210587225-d18108c9-e40c-4262-84d9-56f08a047c4f.png)

**Comment by trevorcampbell** [comment]
There is a good reason: we need to write to `source/` as the `jovyan` user inside the docker container. The UID of `jovyan` doesn't necessarily align with the UID of the user who cloned the repo.

See #82 . If we can avoid writing to `source/` entirely that would be ideal, and would let us avoid making `source/` writable by all -- I am not a fan of writing to `source/` as part of the build process. 

I think the only reason we write to `source/` is related to figures (and I believe only the 3D figures? Maybe I'm wrong), about which you know a lot more than I do. Maybe you can see a better way of handling it?
